### ISSUE TITLE
Crashes node app

### ISSUE THREAD

**Issue by olekenneth** [Hexagon/node-telldus#54]
Hi 

I get this error several times a day. 

    node: ../deps/uv/src/unix/threadpool.c:236: uv__queue_done: Assertion `((&(req->loop)->active_reqs == (&(req->loop)->active_reqs)->prev) == 0)' failed.

I use the Tellstick Duo with firmware 12 on a Debian machine.

**Comment by Z3TA** [comment]
nodejs: ../deps/uv/src/unix/threadpool.c:236: uv__queue_done: Assertion `((&(req->loop)->active_reqs == (&(req->loop)->active_reqs)->prev) == 0)' failed.

uname -m x86_64
nodejs -v v0.10.25

Telldus firmware: 12

**Comment by Z3TA** [comment]
Here's another error:

**Comment by Z3TA** [comment]
Here's some debug info before the error in threadpool.c

2015-11-11 (09:48:08_401 debug: sensorEvent: deviceId=199, protocol=temperaturehumidity, model=fineoffset, type=2 value=43, timestamp=1447231688
2015-11-11 (09:48:15_472 debug: RAW: class:sensor;protocol:fineoffset;id:135;model:temperaturehumidity;humidity:66;temp:8.6;
2015-11-11 (09:48:15_472 debug: sensorEvent: deviceId=135, protocol=temperaturehumidity, model=fineoffset, type=1 value=8.6, timestamp=1447231695
2015-11-11 (09:48:15_472 debug: sensorEvent: deviceId=135, protocol=temperaturehumidity, model=fineoffset, type=2 value=66, timestamp=1447231695
2015-11-11 (09:48:22_624 debug: RAW: class:sensor;protocol:fineoffset;id:215;model:temperaturehumidity;humidity:55;temp:11.6;
2015-11-11 (09:48:22_624 debug: sensorEvent: deviceId=215, protocol=temperaturehumidity, model=fineoffset, type=1 value=11.6, timestamp=1447231702
2015-11-11 (09:48:22_625 debug: sensorEvent: deviceId=215, protocol=temperaturehumidity, model=fineoffset, type=2 value=55, timestamp=1447231702
2015-11-11 (09:48:30_495 debug: RAW: class:sensor;protocol:fineoffset;id:167;model:temperaturehumidity;humidity:41;temp:20.0;
2015-11-11 (09:48:30_496 debug: sensorEvent: deviceId=167, protocol=temperaturehumidity, model=fineoffset, type=1 value=20.0, timestamp=1447231710
2015-11-11 (09:48:30_496 debug: sensorEvent: deviceId=167, protocol=temperaturehumidity, model=fineoffset, type=2 value=41, timestamp=1447231710
2015-11-11 (09:48:39_983 debug: RAW: class:sensor;protocol:fineoffset;id:151;model:temperaturehumidity;humidity:82;temp:5.2;
nodejs: ../deps/uv/src/unix/threadpool.c:236: uv__queue_done: Assertion `((&(req->loop)->active_reqs == (&(req->loop)->active_reqs)->prev) == 0)' failed.

**Comment by Hexagon** [comment]
This seem to be because uv_queue isn't thread safe,i guess the chances of this happening is increasing tremendously if listening to both rawDataEvent and sensorEvent at the same time. As these two happens at the exact same time.

Try that as a workaround, I'll look into a solution when there is time :)

**Comment by Hexagon** [comment]
I just pushed a possible solution for this, where i removed the deletes from reqest objects. Can anyone who had this error try out the latest version on npm?

**Comment by Hexagon** [comment]
A real solution pushed, replace uv_queue_work with uv_async

**Comment by Z3TA** [comment]
I've tested the new version and it no longer crashes, but it randomly  
stops receiving data witch is much worse!

I get around 4-5 sensor events per second but do not notice anything weird  
before it just stops receiving any data.

**Comment by Hexagon** [comment]
How often (in average) does this happen, and in which listener (device/sensor/raw)?

**Comment by Z3TA** [comment]
I've made my app restart if there is no sensor activity (all listeners) for two minutes and that happens about two times per day. I also still get "./deps/uv/src/unix/core.c:161: uv_close: Assertion `0' failed." error message, but only 1-3 times per week.
